apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: crossplane-dev-sea-vnet
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: azure-provider
  forProvider:
    resourceGroupNameRef:
      name: crossplane-dev-sea-rg
    location: Southeast Asia
    addressSpace:
      - 10.2.0.0/16
