apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: crossplane-dev-sea-aks
spec:
  providerConfigRef:
    name: azure-provider
  forProvider:    
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_D2_v2
        vnetSubnetIdRef:
          name: aks-subnet
    dnsPrefix: aks
    identity:
      - type: SystemAssigned
    location: Southeast Asia
    resourceGroupNameRef:
      name: crossplane-dev-sea-rg  
