---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  namespace: crossplane-system
type: Opaque
data:
  creds: W2RlZmF1bHRdDQphd3NfYWNjZXNzX2tleV9pZCA9IEFLSUFYWTdTRzVaS1FTWUxNSUVZDQphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSBhYURmMHQvQ1RDZzQ4TzZtbFlJd2Y2MXJwZmkvWHl5S1UrYk4xYlBLDQo=
