---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name:  ex-eks-nodes-role
spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            }
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: dev-demo-eks-nodes-amazon-eks-worker-node-policy
spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    role: ex-eks-nodes-role
    policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: dev-demo-eks-nodes-amazon-eks-cni-policy
spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    role: ex-eks-nodes-role
    policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: dev-demo-eks-nodes-amazon-ec2-container-registry-read-only
spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    role: ex-eks-nodes-role
    policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly